name: lithuanian-energy-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - linearmodels
  - pulp
  - ipykernel
  - jupyterlab
  - voila
  - ipywidgets
